# Generated by Django 3.2.16 on 2023-02-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('SA', 'Saving Account'), ('CA', 'Current Account')], max_length=20, null=True)),
                ('account_num', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
                ('one_day_float', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
                ('two_day_float', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
                ('last_clearing', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bankdetails')),
            ],
            options={
                'unique_together': {('date', 'description', 'amount')},
            },
        ),
    ]
