# Generated by Django 3.2.16 on 2023-02-23 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_accountdetails_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='is_enabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='last_synced',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='name',
            field=models.CharField(blank=True, default='MayBank', max_length=20, null=True),
        ),
    ]
