# Generated by Django 4.1.7 on 2023-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230223_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountdetails',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('TD', 'TODO'), ('IP', 'In Progress'), ('DN', 'Done')], default='TD', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='trans_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='trans_type',
            field=models.CharField(blank=True, choices=[('CD', 'Credit'), ('DB', 'Debit')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='accountdetails',
            unique_together={('trans_date', 'description', 'amount', 'trans_type')},
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='date',
        ),
    ]
